## **Numpy**
---

#### **배열 생성**

In [5]:
import numpy as np

# 리스트를 넘파이
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
# 타입 확인
type(np.array([1,2,3,4]))

numpy.ndarray

In [6]:
# 상위 타입으로 변환해줌
np.array([1,2,3,4,5.5])

array([1. , 2. , 3. , 4. , 5.5])

In [8]:
# 데이터 타입을 지정
np.array([1,2,4.5,5], dtype='int')

# 타입 지정이 불가능한 경우, 오류가 뜸

array([1, 2, 4, 5])

In [10]:
# 2차원 배열
np.array([[80,90,100],[50,40,100],[70,80,90]])

# 행렬의 크기가 맞지 않다면, 오류가 뜸

array([[ 80,  90, 100],
       [ 50,  40, 100],
       [ 70,  80,  90]])

In [11]:
# 3차원 배열
np.array([[[1,2,3], [4,5,6], [7,8,9]], 
               [[1,2,3], [4,5,6], [7,8,9]], 
               [[1,2,3], [4,5,6], [7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

#### **배열 정보 확인**

In [12]:
a = np.array([[80,90,100],[50,40,100],[70,80,90]])

In [16]:
# shape (배열의 모양/ 행렬)
a.shape

(3, 3)

In [14]:
# dtype( data type 확인)
a.dtype

dtype('int32')

In [15]:
# ndim (차원 확인)
a.ndim

2

In [17]:
# size (배열의 총 원소 개수 확인)
a.size

9

#### **내장으로 있는 배열 생성**

In [22]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.ones((3,2), dtype='int')

array([[1, 1],
       [1, 1],
       [1, 1]])

In [23]:
np.full((3,5), 3.14) # 3.14로 채우기

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [24]:
np.eye(3)  # 단위행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
# 넘파이 0~9 배열 만들기
np.arange(0, 10,2)

array([0, 2, 4, 6, 8])

In [27]:
# 0~1까지 5개의 간격으로
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
# 0~1사이의 배열 무작위 값을 생성
np.random.random(10) 

array([0.16526479, 0.35111503, 0.24226584, 0.88176712, 0.51829347,
       0.71464139, 0.41294333, 0.34375431, 0.51585804, 0.81999194])

In [30]:
# 1~37 무작위 값 생성
np.random.randint(1, 37, (5, 6))

array([[ 7, 21, 14,  2, 30,  4],
       [ 7, 36, 36, 14, 20, 16],
       [19, 20, 26,  7, 20, 30],
       [22, 15, 10,  7,  3,  6],
       [ 2,  9,  4, 34, 29, 13]])

In [33]:
# 표준정규분포 : m=0, std=1
np.random.normal((3,3))

array([2.87473319, 3.14476359])

In [35]:
np.random.normal(10000, 2000, 3)

array([11441.5791928 , 11135.79605248,  9120.30840204])

#### **배열 다루기**

In [36]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [37]:
print(a[0][0])
print(a[1][1])

80
40


In [38]:
# 슬라이싱
print(a1)
print(a1[0:3])

[1 2 3 4 5]
[1 2 3]


In [40]:
print(a2)
print(a2[:])
print(a2[:2, :2])
print(a2[::2, ::2])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[1 3]
 [7 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


#### **배열 요소 수정**

In [41]:
# 인덱싱을 이용해서 수정
a1 = np.array([1,2,3,4,5])
a1[0] = 10
print(a1)
# 슬라이싱을 이용해서 수정
a1[:3] = 5
print(a1)
# 인덱스 배열을 만들어서 수정
idxs = np.array([1,3,4])
a1[idxs] = 7
print(a1)
# 배열과 스칼라 값을 연산 할 수 있음
a1 -= 5
print(a1)

[10  2  3  4  5]
[5 5 5 4 5]
[5 7 5 7 7]
[0 2 0 2 2]


#### **배열 복사**

In [42]:
# 넘파이에서는 copy는 깊은 복사
a = np.array([[1,2,3],[4,5,6]])
b = a.copy()
a[0,0] = 10
print(a)
print(b)

[[10  2  3]
 [ 4  5  6]]
[[1 2 3]
 [4 5 6]]


In [43]:
# 얕은 복사 view
a = np.array([[1,2,3],[4,5,6]])
b = a.view()
a[0,0] = 10
print(a)
print(b)

[[10  2  3]
 [ 4  5  6]]
[[10  2  3]
 [ 4  5  6]]


#### **배열 전치**

In [44]:
# (3,2) => (2,3)
# 행과 열의 크기를 바꾼 배열
a2 = np.array([[1,2,3], [4,5,6]])
print(a2)
print(a2.T)
print(a2.swapaxes(0, 1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


#### **배열 재구조화**

In [45]:
# 1차원 -> 2차원
# size가 맞아야함
a1 = np.arange(1, 10)
print(a1)
print(a1.reshape(3, 3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
# newaxis => 축 (차원)을 만들어주는 것
print(a1[np.newaxis,:])
print(a1[:,np.newaxis])

[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [50]:
# 다차원 배열 => 1차원 배열
# 딥러닝에서 자주 사용하는 스킬
a = np.zeros((3,2,4))
a.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

#### **배열 연결**

In [51]:
a1 = np.arange(1, 3)
b1 = np.arange(3, 5)
c1 = np.arange(5, 7)
print(a1,b1,c1)

[1 2] [3 4] [5 6]


In [52]:
print(np.concatenate([a1, b1]))
print(np.concatenate([a1, b1, c1]))

[1 2 3 4]
[1 2 3 4 5 6]


In [53]:
a2 = np.arange(1, 7).reshape(2, 3)
print(a2)

[[1 2 3]
 [4 5 6]]


In [57]:
# axis default 값 = 0
# 행을 기준으로 concat
print(np.concatenate([a2, a2],axis=0))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [59]:
# 열을 기준으로 concat
print(np.concatenate([a2, a2], axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


#### **배열 연산**

In [61]:
x = np.array([1,2,3,4,5])

In [62]:
x.sum()
x.prod() # 요소들의 곱
x.mean()
np.std(x) # x.std()
x.max()
np.argmax(x) # 최댓값의 인덱스 반환
x.argmin() # 최솟값의 인덱스 반환
np.median(x)

3.0

In [63]:
x = np.random.randint(1, 10, (3,3))
x

array([[8, 2, 8],
       [8, 8, 4],
       [4, 5, 4]])

In [64]:
# 배열의 열을 기준으로 더하는 연산
np.sum(x, axis=1)

array([18, 20, 13])

In [65]:
# 배열의 행을 기준으로 더하는 연산
np.sum(x, axis=0)

array([20, 15, 16])

In [66]:
x = np.arange(1, 11)
y = np.arange(11, 21)

In [67]:
x + y
x-y
x*y
-(x-y) # 부호 반대로 만들기
np.abs(x-y)
np.exp2(x) # 2의 지수함수
np.power(3, x) # 3의 지수함수
np.log(x) # 로그함수

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

#### **비교**

In [68]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
# any -> 하나라도 만족하면 True
np.any(a>5), np.any(a<0)

(True, False)

In [70]:
# all -> 모두 만족하면 True, 하나라도 불만족하면 False
np.all(a>5), np.all(a<10)

(False, True)

In [71]:
# 넘파이는 배열의 크기가 동일 할 때 요소간의 비교의 결과를 불 타입으로 반환
a = np.array([1,3,0])
b = np.array([5,2,1])
a>b

array([False,  True, False])

In [72]:
# where을 이용한 비교
# 조건, 참 값, 거짓 값
np.where(a>0,'T','F')

array(['T', 'T', 'F'], dtype='<U1')

#### **Boolean, Fancy index**

In [73]:
# 넘파이 배열은 특정 조건에 따른 값을 배열 형태로 추출 가능
a = np.array([1,4,0,2,3,8,9,7])
a>3

array([False,  True, False, False, False,  True,  True,  True])

In [74]:
# 참, 거짓 조건을 이용해서 값 추출 => Boolean index
# 딥러닝에서 파라미터나 결과가 임계점을 넘지 않는 값을 제거할 때 자주사용
a[a>3]

array([4, 8, 9, 7])

In [75]:
# 넘파이는 배열을 index value로 사용해서 값을 추출 할 수 있음 => Fancy index
a = np.array([2,4,6,8])
b = np.array([0,0,1,3,2,1])
a[b]

array([2, 2, 4, 8, 6, 4])